// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PocRelatorio.API.Contexts;

namespace PocRelatorio.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210707205504_RelatorioDb")]
    partial class RelatorioDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PocRelatorio.API.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodigoCliente")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantidadeTitulos")
                        .HasColumnType("int");

                    b.Property<double>("TotalPago")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cnpj = "99.99.999/9999-99",
                            CodigoCliente = 105,
                            Nome = "Cliente teste",
                            QuantidadeTitulos = 2,
                            TotalPago = 7062.0
                        },
                        new
                        {
                            Id = 2,
                            Cnpj = "88.88.888/8888-88",
                            CodigoCliente = 1752,
                            Nome = "Farmácia A",
                            QuantidadeTitulos = 2,
                            TotalPago = 2022.0
                        },
                        new
                        {
                            Id = 3,
                            Cnpj = "77.77.777/7777-77",
                            CodigoCliente = 45879,
                            Nome = "Roupas B",
                            QuantidadeTitulos = 6,
                            TotalPago = 35202.699999999997
                        },
                        new
                        {
                            Id = 4,
                            Cnpj = "88.88.888/8888-88",
                            CodigoCliente = 1753,
                            Nome = "Farmácia C",
                            QuantidadeTitulos = 2,
                            TotalPago = 812.0
                        });
                });

            modelBuilder.Entity("PocRelatorio.API.FormaPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Administradora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("DataPagamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescricaoTipoPagamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LancamentoContabil")
                        .HasColumnType("bigint");

                    b.Property<long>("NSU")
                        .HasColumnType("bigint");

                    b.Property<long>("NumeroAutorizacao")
                        .HasColumnType("bigint");

                    b.Property<string>("QuantidadeParcelas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("FormasPagamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Administradora = "VISA",
                            ClienteId = 1,
                            DataPagamento = "20/04/2021",
                            DescricaoTipoPagamento = "Cartão de Crédito",
                            LancamentoContabil = 1452656L,
                            NSU = 785423658L,
                            NumeroAutorizacao = 12457L,
                            QuantidadeParcelas = "2x",
                            Valor = 1062.0
                        },
                        new
                        {
                            Id = 2,
                            Administradora = "Master",
                            ClienteId = 1,
                            DataPagamento = "20/04/2021",
                            DescricaoTipoPagamento = "Cartão de Crédito",
                            LancamentoContabil = 1452656L,
                            NSU = 15549662L,
                            NumeroAutorizacao = 12345L,
                            QuantidadeParcelas = "8x",
                            Valor = 6000.0
                        },
                        new
                        {
                            Id = 3,
                            Administradora = "Master",
                            ClienteId = 2,
                            DataPagamento = "22/04/2021",
                            DescricaoTipoPagamento = "Cartão de Crédito",
                            LancamentoContabil = 1426587L,
                            NSU = 5847562L,
                            NumeroAutorizacao = 65251L,
                            QuantidadeParcelas = "2x",
                            Valor = 2000.0
                        },
                        new
                        {
                            Id = 4,
                            Administradora = "VISA",
                            ClienteId = 3,
                            DataPagamento = "23/04/2021",
                            DescricaoTipoPagamento = "Cartão de Crédito",
                            LancamentoContabil = 1457895L,
                            NSU = 48756235L,
                            NumeroAutorizacao = 254566L,
                            QuantidadeParcelas = "10X",
                            Valor = 30000.0
                        },
                        new
                        {
                            Id = 5,
                            Administradora = "_",
                            ClienteId = 3,
                            DataPagamento = "23/04/2021",
                            DescricaoTipoPagamento = "PIX",
                            LancamentoContabil = 1457895L,
                            NSU = 0L,
                            NumeroAutorizacao = 0L,
                            QuantidadeParcelas = "1X",
                            Valor = 5202.6999999999998
                        },
                        new
                        {
                            Id = 6,
                            Administradora = "Master",
                            ClienteId = 4,
                            DataPagamento = "23/04/2021",
                            DescricaoTipoPagamento = "Cartão de Crédito",
                            LancamentoContabil = 1245862L,
                            NSU = 499654756L,
                            NumeroAutorizacao = 551225L,
                            QuantidadeParcelas = "6X",
                            Valor = 812.0
                        });
                });

            modelBuilder.Entity("PocRelatorio.API.TitulosRenegociados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<double>("Juros")
                        .HasColumnType("float");

                    b.Property<double>("Multa")
                        .HasColumnType("float");

                    b.Property<int>("NumeroTituloRenegociado")
                        .HasColumnType("int");

                    b.Property<string>("Parcela")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ValorAtualizado")
                        .HasColumnType("float");

                    b.Property<double>("ValorOriginalTitulo")
                        .HasColumnType("float");

                    b.Property<string>("Vencimento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Titulos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 1,
                            Juros = 20.0,
                            Multa = 2.0,
                            NumeroTituloRenegociado = 123456,
                            Parcela = "A",
                            ValorAtualizado = 2022.0,
                            ValorOriginalTitulo = 2000.0,
                            Vencimento = "01/01/2020"
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 1,
                            Juros = 35.0,
                            Multa = 5.0,
                            NumeroTituloRenegociado = 555559,
                            Parcela = "B",
                            ValorAtualizado = 5040.0,
                            ValorOriginalTitulo = 5000.0,
                            Vencimento = "01/03/2020"
                        },
                        new
                        {
                            Id = 3,
                            ClienteId = 2,
                            Juros = 20.0,
                            Multa = 2.0,
                            NumeroTituloRenegociado = 123456,
                            Parcela = "A",
                            ValorAtualizado = 2022.0,
                            ValorOriginalTitulo = 2000.0,
                            Vencimento = "01/01/2020"
                        },
                        new
                        {
                            Id = 4,
                            ClienteId = 3,
                            Juros = 5.0,
                            Multa = 2.0,
                            NumeroTituloRenegociado = 152365,
                            Parcela = "A",
                            ValorAtualizado = 257.0,
                            ValorOriginalTitulo = 250.0,
                            Vencimento = "25/03/2020"
                        },
                        new
                        {
                            Id = 5,
                            ClienteId = 3,
                            Juros = 12.0,
                            Multa = 3.0,
                            NumeroTituloRenegociado = 556685,
                            Parcela = "B",
                            ValorAtualizado = 3265.0,
                            ValorOriginalTitulo = 3250.0,
                            Vencimento = "14/07/2020"
                        },
                        new
                        {
                            Id = 6,
                            ClienteId = 3,
                            Juros = 7.0,
                            Multa = 2.5,
                            NumeroTituloRenegociado = 776458,
                            Parcela = "B",
                            ValorAtualizado = 754.5,
                            ValorOriginalTitulo = 745.0,
                            Vencimento = "13/05/2020"
                        },
                        new
                        {
                            Id = 7,
                            ClienteId = 3,
                            Juros = 35.0,
                            Multa = 2.5,
                            NumeroTituloRenegociado = 574125,
                            Parcela = "D",
                            ValorAtualizado = 2337.5,
                            ValorOriginalTitulo = 2300.0,
                            Vencimento = "15/06/2020"
                        },
                        new
                        {
                            Id = 8,
                            ClienteId = 3,
                            Juros = 1500.0,
                            Multa = 300.0,
                            NumeroTituloRenegociado = 219453,
                            Parcela = "A",
                            ValorAtualizado = 26800.0,
                            ValorOriginalTitulo = 25000.0,
                            Vencimento = "22/03/2021"
                        },
                        new
                        {
                            Id = 9,
                            ClienteId = 4,
                            Juros = 15.0,
                            Multa = 5.0,
                            NumeroTituloRenegociado = 123456,
                            Parcela = "A",
                            ValorAtualizado = 520.0,
                            ValorOriginalTitulo = 500.0,
                            Vencimento = "01/01/2020"
                        },
                        new
                        {
                            Id = 10,
                            ClienteId = 4,
                            Juros = 35.0,
                            Multa = 7.0,
                            NumeroTituloRenegociado = 55559,
                            Parcela = "B",
                            ValorAtualizado = 292.0,
                            ValorOriginalTitulo = 250.0,
                            Vencimento = "01/03/2020"
                        });
                });

            modelBuilder.Entity("PocRelatorio.API.FormaPagamento", b =>
                {
                    b.HasOne("PocRelatorio.API.Cliente", "Cliente")
                        .WithMany("FormaPagamentos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("PocRelatorio.API.TitulosRenegociados", b =>
                {
                    b.HasOne("PocRelatorio.API.Cliente", "Cliente")
                        .WithMany("Titulos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("PocRelatorio.API.Cliente", b =>
                {
                    b.Navigation("FormaPagamentos");

                    b.Navigation("Titulos");
                });
#pragma warning restore 612, 618
        }
    }
}
